Third 5
F1iper/The-HR-Division pull request #11
Opened 2022-03-09 17:45 UTC by dylionen

Prośba o code review

2022-03-10 13:03 UTC, a-dubaj approved these changes
Looks ok

2022-03-10 15:49 UTC, F1iper requested changes

2022-03-10 15:49 UTC, F1iper commented on src/main/java/com/thehrdivision/Employee.java
> +    private int id;
Używasz typu prymitywnego, którego domyślna wartość to 0, w docs'ach Hibernate'a krótkie wyjaśnienie  -> https://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#entity-pojo-identifier

2022-03-10 15:49 UTC, F1iper commented on src/main/java/com/thehrdivision/UserEntity.java
> +    @NotNull
Niestety przy tej adnotacji nadal jest opcja włożenia NULL'a do tabeli, u mnie to wygląda tak ->
![Screenshot from 2022-03-10 15-37-31](https://user-images.githubusercontent.com/59711082/157687045-bc9eed60-899a-4c02-a5ed-572443177442.png)
![Screenshot from 2022-03-10 15-47-25](https://user-images.githubusercontent.com/59711082/157687088-35c21c21-813c-4904-a5c3-aeccf55fcb9f.png)

Na szybko zrobiłem test adnotacji @Column(nullable = false) 
Tak to wygląda -> 
![Screenshot from 2022-03-10 15-51-16](https://user-images.githubusercontent.com/59711082/157687572-09691f84-f6d0-46f1-a10c-6c9c7aaa0072.png)
i dostałem wynik -> 

![Screenshot from 2022-03-10 15-51-01](https://user-images.githubusercontent.com/59711082/157687492-80afd7cf-4b89-479e-a17e-e81b5b6c5c48.png)

Przykładowa implementacja -> https://www.baeldung.com/hibernate-notnull-vs-nullable

Więcej info -> https://stackoverflow.com/questions/4963300/which-notnull-java-annotation-should-i-use

2022-03-10 15:49 UTC, F1iper commented on src/main/java/com/thehrdivision/UserEntity.java
> +    @OneToOne()
Clean up :cow2:  ( )

2022-03-10 15:49 UTC, F1iper commented on src/main/java/com/thehrdivision/UserEntity.java
> +    private Date createdAt;
Tutaj wydaje mi się, że chcemy aby to pole zostało "zasilone" podczas insertu rekordu do bazy danych, tutaj więcej info -> 
https://stackoverflow.com/questions/221611/creation-timestamp-and-last-update-timestamp-with-hibernate-and-mysql/221827#221827

https://www.javafixing.com/2021/11/fixed-createddate-annotation-does-not.html

Co do typu Date, to tu któtki artykuł -> https://programminghints.com/2017/05/still-using-java-util-date-dont/

2022-03-10 15:49 UTC, F1iper commented on src/main/java/com/thehrdivision/UserEntity.java
> +    private int id;
Link w komentarzu do klasy ```Position```

2022-03-10 15:49 UTC, F1iper commented on src/main/java/com/thehrdivision/Position.java
> +    private int id;
Link w komentarzu do klasy ```Position```

2022-03-12 14:59 UTC, F1iper approved these changes
Annotations works fine now, looks good to me.

2022-03-12 15:00 UTC, merged